Force Files.DeleteDirVisitor instantiation to avoid NCDFE (#85)
Moved DeleteDirVisitor instance to Files, so it's loaded before
shutdown hook starts and avoids NoClassDefFoundError.

Fixes #36