Force Files.DeleteDirVisitor instantiation to avoid NCDFE
Moved DeleteDirVisitor instance to Files, so it's loaded before
shutdown hook starts and avoids NoClassDefFoundError.

Fixes #36